Ci 404 follow up changes because worksheet changed
SkillsFundingAgency/das-ofsted-inspection-client pull request #1
Opened 2017-10-25 14:36 UTC by MarkFCain

2017-10-26 14:59 UTC, arvinthseran approved these changes

2017-10-26 14:59 UTC, arvinthseran commented on src/Esfa.Ofsted.Inspection.Client/Services/OverallEffectivenessProcessor.cs
>                      return OverallEffectiveness.NotJudged;
can we add `case "Null":` as well?

2017-10-26 14:59 UTC, arvinthseran commented on src/Esfa.Ofsted.Inspection.UnitTests/OverallEffectivenessProcessorTests.cs
>          public void ShouldReturnStringModifiedForUrlUsage(string inputText, OverallEffectiveness expectedEffectiveness)
`[TestCase("Null", OverallEffectiveness.NotJudged)]` ?

2017-10-27 08:01 UTC, MarkFCain commented on src/Esfa.Ofsted.Inspection.UnitTests/OverallEffectivenessProcessorTests.cs
>          public void ShouldReturnStringModifiedForUrlUsage(string inputText, OverallEffectiveness expectedEffectiveness)
Yeah, I'll do this after I do the logs

2017-10-27 09:40 UTC, scottcowan requested changes
feel free to merge after this

2017-10-27 09:40 UTC, scottcowan commented on src/Esfa.Ofsted.Inspection.Client/Services/GetOfstedDetailsFromExcelPackageService.cs
> +                error.Message = error.Message + $@"Invalid value for Overall Effectiveness [{ error.OverallEffectiveness}]; ";
could you add some { } here

2017-10-27 10:23 UTC, merged